// Cancer type categorization with color coding per category
export const CANCER_CATEGORIES = {
  carcinoma: {
    label: "Carcinoma",
    badge: "bg-blue-50 text-blue-700 border border-blue-200",
    dot: "bg-blue-500",
    bar: "bg-blue-500",
    soft: "bg-blue-50",
    text: "text-blue-700",
  },
  sarcoma: {
    label: "Sarcoma",
    badge: "bg-amber-50 text-amber-700 border border-amber-200",
    dot: "bg-amber-500",
    bar: "bg-amber-500",
    soft: "bg-amber-50",
    text: "text-amber-700",
  },
  hematological: {
    label: "Hematological",
    badge: "bg-rose-50 text-rose-700 border border-rose-200",
    dot: "bg-rose-500",
    bar: "bg-rose-500",
    soft: "bg-rose-50",
    text: "text-rose-700",
  },
  cns: {
    label: "CNS",
    badge: "bg-violet-50 text-violet-700 border border-violet-200",
    dot: "bg-violet-500",
    bar: "bg-violet-500",
    soft: "bg-violet-50",
    text: "text-violet-700",
  },
  neuroendocrine: {
    label: "Neuroendocrine",
    badge: "bg-emerald-50 text-emerald-700 border border-emerald-200",
    dot: "bg-emerald-500",
    bar: "bg-emerald-500",
    soft: "bg-emerald-50",
    text: "text-emerald-700",
  },
  embryonal: {
    label: "Embryonal",
    badge: "bg-fuchsia-50 text-fuchsia-700 border border-fuchsia-200",
    dot: "bg-fuchsia-500",
    bar: "bg-fuchsia-500",
    soft: "bg-fuchsia-50",
    text: "text-fuchsia-700",
  },
};

export const CANCER_TYPES = [
  // Carcinomas (Epithelial / Organ Cancers)
  { value: "Adenocarcinoma", category: "carcinoma" },
  { value: "Squamous Cell Carcinoma", category: "carcinoma" },
  { value: "Basal Cell Carcinoma", category: "carcinoma" },
  { value: "Transitional Cell Carcinoma", category: "carcinoma" },
  { value: "Renal Cell Carcinoma", category: "carcinoma" },
  { value: "Hepatocellular Carcinoma", category: "carcinoma" },
  { value: "Bile Duct Cancer", category: "carcinoma" },
  { value: "Bladder Cancer", category: "carcinoma" },
  { value: "Breast Cancer", category: "carcinoma" },
  { value: "Ductal Carcinoma In Situ", category: "carcinoma" },
  { value: "Male Breast Cancer", category: "carcinoma" },
  { value: "Colorectal Cancer", category: "carcinoma" },
  { value: "Rectal Cancer", category: "carcinoma" },
  { value: "Anal Cancer", category: "carcinoma" },
  { value: "Gastric Cancer", category: "carcinoma" },
  { value: "Esophageal Cancer", category: "carcinoma" },
  { value: "Gallbladder Cancer", category: "carcinoma" },
  { value: "Pancreatic Cancer", category: "carcinoma" },
  { value: "Lung Cancer", category: "carcinoma" },
  { value: "Non-Small Cell Lung Cancer", category: "carcinoma" },
  { value: "Small Cell Lung Cancer", category: "carcinoma" },
  { value: "Mesothelioma", category: "carcinoma" },
  { value: "Cervical Cancer", category: "carcinoma" },
  { value: "Endometrial Cancer", category: "carcinoma" },
  { value: "Ovarian Cancer", category: "carcinoma" },
  { value: "Fallopian Tube Cancer", category: "carcinoma" },
  { value: "Primary Peritoneal Cancer", category: "carcinoma" },
  { value: "Vaginal Cancer", category: "carcinoma" },
  { value: "Vulvar Cancer", category: "carcinoma" },
  { value: "Prostate Cancer", category: "carcinoma" },
  { value: "Penile Cancer", category: "carcinoma" },
  { value: "Thyroid Cancer", category: "carcinoma" },
  { value: "Parathyroid Cancer", category: "carcinoma" },
  { value: "Thymoma and Thymic Carcinoma", category: "carcinoma" },
  { value: "Head and Neck Cancer", category: "carcinoma" },
  { value: "Lip and Oral Cavity Cancer", category: "carcinoma" },
  { value: "Laryngeal Cancer", category: "carcinoma" },
  { value: "Nasal Cavity and Paranasal Sinus Cancer", category: "carcinoma" },
  { value: "Nasopharyngeal Cancer", category: "carcinoma" },
  { value: "Oropharyngeal Cancer", category: "carcinoma" },
  { value: "Hypopharyngeal Cancer", category: "carcinoma" },
  { value: "Salivary Gland Cancer", category: "carcinoma" },
  { value: "Esthesioneuroblastoma", category: "carcinoma" },
  { value: "Skin Cancer", category: "carcinoma" },
  { value: "Carcinoma of Unknown Primary", category: "carcinoma" },
  { value: "Metastatic Cancer", category: "carcinoma" },
  { value: "Metastatic Squamous Neck Cancer with Occult Primary", category: "carcinoma" },
  { value: "Midline Tract Carcinoma With NUT Gene Changes", category: "carcinoma" },
  { value: "Urethral Cancer", category: "carcinoma" },
  { value: "Transitional Cell Cancer of the Renal Pelvis and Ureter", category: "carcinoma" },
  { value: "Adrenocortical Carcinoma", category: "carcinoma" },
  { value: "Small Intestine Cancer", category: "carcinoma" },
  { value: "Appendix Cancer", category: "carcinoma" },

  // Sarcomas (Connective, Bone and Soft Tissue Cancers)
  { value: "Osteosarcoma", category: "sarcoma" },
  { value: "Chondrosarcoma", category: "sarcoma" },
  { value: "Leiomyosarcoma", category: "sarcoma" },
  { value: "Rhabdomyosarcoma", category: "sarcoma" },
  { value: "Liposarcoma", category: "sarcoma" },
  { value: "Angiosarcoma", category: "sarcoma" },
  { value: "Ewing Sarcoma", category: "sarcoma" },
  { value: "Gastrointestinal Stromal Tumor", category: "sarcoma" },
  { value: "Soft Tissue Sarcoma", category: "sarcoma" },
  { value: "Uterine Sarcoma", category: "sarcoma" },
  { value: "Kaposi Sarcoma", category: "sarcoma" },
  { value: "Vascular Tumors", category: "sarcoma" },
  { value: "Malignant Fibrous Histiocytoma", category: "sarcoma" },
  { value: "Chordoma", category: "sarcoma" },
  { value: "Pleuropulmonary Blastoma", category: "sarcoma" },

  // Hematological Malignancies (Blood Cancers)
  { value: "Acute Lymphoblastic Leukemia", category: "hematological" },
  { value: "Acute Myeloid Leukemia", category: "hematological" },
  { value: "Chronic Lymphocytic Leukemia", category: "hematological" },
  { value: "Chronic Myelogenous Leukemia", category: "hematological" },
  { value: "Hairy Cell Leukemia", category: "hematological" },
  { value: "Hodgkin Lymphoma", category: "hematological" },
  { value: "Non-Hodgkin Lymphoma", category: "hematological" },
  { value: "Burkitt Lymphoma", category: "hematological" },
  { value: "AIDS-Related Lymphoma", category: "hematological" },
  { value: "Primary CNS Lymphoma", category: "hematological" },
  { value: "Cutaneous T-Cell Lymphoma", category: "hematological" },
  { value: "Mycosis Fungoides", category: "hematological" },
  { value: "Sezary Syndrome", category: "hematological" },
  { value: "Multiple Myeloma", category: "hematological" },
  { value: "Plasma Cell Neoplasm", category: "hematological" },
  { value: "Myelodysplastic Syndromes", category: "hematological" },
  { value: "Myeloproliferative Neoplasms", category: "hematological" },
  { value: "Langerhans Cell Histiocytosis", category: "hematological" },

  // Central Nervous System Malignancies
  { value: "Glioblastoma Multiforme", category: "cns" },
  { value: "Astrocytoma", category: "cns" },
  { value: "Diffuse Intrinsic Pontine Glioma", category: "cns" },
  { value: "Anaplastic Oligodendroglioma", category: "cns" },
  { value: "Ependymoma", category: "cns" },
  { value: "Medulloblastoma", category: "cns" },
  { value: "Craniopharyngioma", category: "cns" },
  { value: "Atypical Teratoid/Rhabdoid Tumor", category: "cns" },
  { value: "Brain Tumor", category: "cns" },
  { value: "Pituitary Tumor", category: "cns" },
  { value: "Childhood CNS Germ Cell Tumor", category: "cns" },

  // Neuroendocrine & Specialized Cell Tumors
  { value: "Malignant Melanoma", category: "neuroendocrine" },
  { value: "Intraocular Melanoma", category: "neuroendocrine" },
  { value: "Merkel Cell Carcinoma", category: "neuroendocrine" },
  { value: "Pheochromocytoma", category: "neuroendocrine" },
  { value: "Carcinoid Tumor", category: "neuroendocrine" },
  { value: "Gastrointestinal Neuroendocrine Tumors", category: "neuroendocrine" },
  { value: "Pancreatic Neuroendocrine Tumors", category: "neuroendocrine" },
  { value: "Islet Cell Tumors", category: "neuroendocrine" },
  { value: "Paraganglioma", category: "neuroendocrine" },

  // Embryonal & Germ Cell Cancers
  { value: "Seminoma", category: "embryonal" },
  { value: "Choriocarcinoma", category: "embryonal" },
  { value: "Retinoblastoma", category: "embryonal" },
  { value: "Wilms Tumor", category: "embryonal" },
  { value: "Neuroblastoma", category: "embryonal" },
  { value: "Testicular Cancer", category: "embryonal" },
  { value: "Ovarian Germ Cell Tumor", category: "embryonal" },
  { value: "Extracranial Germ Cell Tumor", category: "embryonal" },
  { value: "Extragonadal Germ Cell Tumor", category: "embryonal" },
  { value: "Gestational Trophoblastic Disease", category: "embryonal" },
  { value: "Childhood Cardiac Tumor", category: "embryonal" },
  { value: "Eye Cancer", category: "embryonal" },
];

const typeToCategory = Object.fromEntries(CANCER_TYPES.map((t) => [t.value, t.category]));

export function getCategory(type) {
  return typeToCategory[type] || "carcinoma";
}

export function getCategoryStyle(type) {
  return CANCER_CATEGORIES[getCategory(type)] || CANCER_CATEGORIES.carcinoma;
}

export const CANCER_TYPE_OPTIONS = CANCER_TYPES.map((t) => t.value);